-- Station-membership applications and time-bounded entitlements.
CREATE TABLE `StationMembershipRequest` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `stationId` VARCHAR(191) NOT NULL,
    `status` ENUM('PENDING_REVIEW', 'PAYMENT_PENDING', 'PAYMENT_RECEIVED', 'APPROVED', 'REJECTED', 'CANCELLED') NOT NULL DEFAULT 'PENDING_REVIEW',
    `paymentAmount` DECIMAL(12, 2) NULL,
    `paymentReference` VARCHAR(191) NULL,
    `paymentNotes` TEXT NULL,
    `paymentReceivedAt` DATETIME(3) NULL,
    `paymentReceivedByAdminId` VARCHAR(191) NULL,
    `requestedDurationDays` INTEGER NULL,
    `reviewedAt` DATETIME(3) NULL,
    `reviewedByAdminId` VARCHAR(191) NULL,
    `rejectionReason` TEXT NULL,
    `adminNotes` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `StationMembershipRequest_userId_status_idx`(`userId`, `status`),
    INDEX `StationMembershipRequest_stationId_status_idx`(`stationId`, `status`),
    INDEX `StationMembershipRequest_status_createdAt_idx`(`status`, `createdAt`),
    CONSTRAINT `StationMembershipRequest_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `StationMembershipRequest_stationId_fkey` FOREIGN KEY (`stationId`) REFERENCES `Station`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `StationMembership` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `stationId` VARCHAR(191) NOT NULL,
    `requestId` VARCHAR(191) NULL,
    `discountRate` DECIMAL(5, 2) NOT NULL,
    `status` ENUM('ACTIVE', 'REVOKED', 'EXPIRED') NOT NULL DEFAULT 'ACTIVE',
    `startsAt` DATETIME(3) NOT NULL,
    `expiresAt` DATETIME(3) NOT NULL,
    `approvedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `approvedByAdminId` VARCHAR(191) NOT NULL,
    `revokedAt` DATETIME(3) NULL,
    `revokedByAdminId` VARCHAR(191) NULL,
    `revocationReason` TEXT NULL,
    `adminNotes` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `StationMembership_requestId_key`(`requestId`),
    UNIQUE INDEX `StationMembership_userId_stationId_key`(`userId`, `stationId`),
    INDEX `StationMembership_stationId_status_expiresAt_idx`(`stationId`, `status`, `expiresAt`),
    INDEX `StationMembership_userId_status_expiresAt_idx`(`userId`, `status`, `expiresAt`),
    CONSTRAINT `StationMembership_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `StationMembership_stationId_fkey` FOREIGN KEY (`stationId`) REFERENCES `Station`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `StationMembership_requestId_fkey` FOREIGN KEY (`requestId`) REFERENCES `StationMembershipRequest`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
